language: node_js
node_js:
  - "node"

cache:
  - npm
  - yarn

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
    - eval "${MATRIX_EVAL}"

install:
  - npm install

script:
  - au buildcomp
  - au build
  - au test

# 03/2020 tomask: commented deploy - need to analyze and assess compare with default gh-pages autodeploy
#before_deploy:
#  - mv dist website/build/bodylight.js/composer

#deploy:
#  provider: pages
#  skip-cleanup: true
#  github-token: $GITHUB_TOKEN
#  local-dir: website/build/bodylight.js
#  repo: creative-connections/creative-connections.github.io
#  target-branch: master
#  on:
#    branch: master
