export const SELECT_SCREEN = 'SELECT_SCREEN'
export const NEW_PROJECT = 'NEW_PROJECT'

export const CNFSCR_SELECT_MODEL = 'CNFSCR_SELECT_MODEL'
export const CNFSCR_SELECT_ANIMATE = 'CNFSCR_SELECT_ANIMATE'

export const ADD_MODEL = 'ADD_MODEL'
export const ADD_ANIMATE = 'ADD_ANIMATE'
