export const SELECT_SCREEN = 'SELECT_SCREEN'
export const NEW_PROJECT = 'NEW_PROJECT'

export const CNFSCR_SELECT_MODEL = 'CNFSCR_SELECT_MODEL'
export const CNFSCR_SELECT_ANIMATE = 'CNFSCR_SELECT_ANIMATE'

export const ADD_MODEL = 'ADD_MODEL'
export const ADD_ANIMATE = 'ADD_ANIMATE'

export const ADD_RANGE = 'ADD_RANGE'
export const RENAME_RANGE = 'RENAME_RANGE'
export const REMOVE_RANGE = 'REMOVE_RANGE'

export const ADD_BUTTON = 'ADD_BUTTON'
export const RENAME_BUTTON = 'RENAME_BUTTON'
export const REMOVE_BUTTON = 'REMOVE_BUTTON'

export const SELECT_WIDGET = 'SELECT_WIDGET'

export const CONFIG_ANIMATE_ANIM_UPDATE = 'CONFIG_ANIMATE_ANIM_UPDATE'

export const CONFIG_ANIMATE_TEXT_UPDATE = 'CONFIG_ANIMATE_TEXT_UPDATE'
export const CONFIG_ANIMATE_TEXT_REMOVE = 'CONFIG_ANIMATE_TEXT_REMOVE'

export const CONFIG_RANGE_UPDATE = 'CONFIG_RANGE_UPDATE'
export const CONFIG_RANGE_REMOVE = 'CONFIG_RANGE_REMOVE'

export const CONFIG_BUTTON_UPDATE = 'CONFIG_BUTTON_UPDATE'
export const CONFIG_BUTTON_REMOVE = 'CONFIG_BUTTON_REMOVE'

export const EDITOR_STORAGE_STORE = 'EDITOR_STORAGE_STORE'
export const EDITOR_STORAGE_CLEAR = 'EDITOR_STORAGE_CLEAR'

export const EDITOR_PLACE_ANIMATE = 'EDITOR_PLACE_ANIMATE'
export const EDITOR_REMOVE_ANIMATE = 'EDITOR_REMOVE_ANIMATE'
export const EDITOR_PLACE_RANGE = 'EDITOR_PLACE_RANGE'
export const EDITOR_REMOVE_RANGE = 'EDITOR_REMOVE_RANGE'

export const FUNCTION_EDITOR_CONFIG_CHANGE = 'FUNCTION_EDITOR_CONFIG_CHANGE'
