const WidgetType = {
  MODEL: 'MODEL',
  ANIMATE: 'ANIMATE',
  ANIMATE_ANIM: 'ANIMATE_ANIM',
  ANIMATE_TEXT: 'ANIMATE_TEXT',
  RANGE: 'RANGE',
  BUTTON: 'BUTTON',
  ACTION: 'ACTION',
  TOGGLE: 'TOGGLE',
  CHART: 'CHART',
  LABEL: 'LABEL',
  CSS: 'CSS',
  JAVASCRIPT: 'JAVASCRIPT'
}

export default WidgetType
