const WidgetType = {
  MODEL: 'MODEL',
  ANIMATE: 'ANIMATE',
  ANIMATE_ANIM: 'ANIMATE_ANIM',
  ANIMATE_TEXT: 'ANIMATE_TEXT',
  RANGE: 'RANGE',
  BUTTON: 'BUTTON',
  ACTION: 'ACTION'
}

export default WidgetType
