import React from 'react'
import SimpleList from '@components/SimpleList'
import { Segment, Grid, Header, List } from 'semantic-ui-react'

const transformElementsToArray = (elements) => {
  const data = []
  Object.keys(elements).forEach((el) => {
    data.push(elements[el].name)
  })
  return data
}

const ModelInfo = ({modelDescription = null}) => {
  if (modelDescription !== null) {
    return (
      <div>
        <Grid columns={3} stretched >
          <Grid.Row>
            <Grid.Column>
              <Header as="h4">Model info</Header>
              <List>
                <List.Item>
                  <List.Icon name='font' />
                  <List.Content>
                    <List.Header>Model name</List.Header>
                    <List.Description>{modelDescription.modelName}</List.Description>
                  </List.Content>
                </List.Item>
                <List.Item>
                  <List.Icon name='bold' />
                  <List.Content>
                    <List.Header>Model identifier</List.Header>
                    <List.Description>{modelDescription.modelIdentifier}</List.Description>
                  </List.Content>
                </List.Item>
                <List.Item>
                  <List.Icon name='sticky note' />
                  <List.Content>
                    <List.Header>Description</List.Header>
                    <List.Description>{modelDescription.description}</List.Description>
                  </List.Content>
                </List.Item>
                <List.Item>
                  <List.Icon name='barcode' />
                  <List.Content>
                    <List.Header>GUID</List.Header>
                    <List.Description>{modelDescription.guid}</List.Description>
                  </List.Content>
                </List.Item>
                <List.Item>
                  <List.Icon name='wrench' />
                  <List.Content>
                    <List.Header>Generated by</List.Header>
                    <List.Description>{modelDescription.generationTool}</List.Description>
                  </List.Content>
                </List.Item>
                <List.Item>
                  <List.Icon name='calendar alternate' />
                  <List.Content>
                    <List.Header>Generated on</List.Header>
                    <List.Description>{modelDescription.generationDateAndTime}</List.Description>
                  </List.Content>
                </List.Item>
              </List>
            </Grid.Column>

            <Grid.Column>
              <Header as="h4">Parameters</Header>
              <Segment style={{overflow: 'auto', maxHeight: 20 + 'em'}}>
                <SimpleList
                  rootname="parameters"
                  data={transformElementsToArray(modelDescription.parameters)}
                />
              </Segment>
            </Grid.Column>

            <Grid.Column>
              <Header as="h4">Variables</Header>
              <Segment style={{overflow: 'auto', maxHeight: 20 + 'em'}}>
                <SimpleList
                  rootname="variables"
                  data={transformElementsToArray(modelDescription.variables)}
                />
              </Segment>
            </Grid.Column>
          </Grid.Row>

        </Grid>
      </div>
    )
  }
  return null
}

export default ModelInfo
